tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "aria2"
brew "fzf"
brew "git"
brew "htop"
brew "jq"
brew "mas"
brew "neovim"
brew "nvm"
brew "rcm"
brew "rsync"
brew "tmux"
brew "zsh"
cask "docker"
cask "kitty"
cask "miniconda"
cask "spotify"
cask "visual-studio-code"

mas "NordVPN", id: 905953485
mas "Telegram", id: 747648890
