
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="lambda"


# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"


pluings=(python yarn docker)
plugins+=(fzf kubectl)
# plugins+=(zsh-completions)


autoload -U compinit && compinit
autoload -U +X bashcompinit && bashcompinit

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'

export TERMINAL=kitty

source /usr/share/nvm/init-nvm.sh

source $HOME/.zshrc.d/alises.zsh
source $HOME/.zshrc.d/functions.zsh
source $HOME/.zshrc.d/plugins.zsh

#export PATH="$(yarn global bin):$PATH"

eval $(keychain --eval --quiet id_rsa yc_static_2)

# The next line updates PATH for Yandex Cloud CLI.
if [ -f '/home/m-nny/yandex-cloud/path.bash.inc' ]; then source '/home/m-nny/yandex-cloud/path.bash.inc'; fi

# The next line enables shell command completion for yc.
if [ -f '/home/m-nny/yandex-cloud/completion.zsh.inc' ]; then source '/home/m-nny/yandex-cloud/completion.zsh.inc'; fi

