# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="lambda"


# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"


pluings=(python yarn docker)
plugins+=(fzf)
plugins+=(zsh-autosuggestions)


autoload -U compinit && compinit
autoload -U +X bashcompinit && bashcompinit

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'

export TERMINAL=kitty

export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
#  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion


source $HOME/.zshrc.d/alises.zsh
source $HOME/.zshrc.d/functions.zsh
source $HOME/.zshrc.d/plugins.zsh

if type yarn > /dev/null; then
  export PATH="$(yarn global bin):$PATH"
fi

#eval $(keychain --eval --quiet id_ed25519)

# The next line updates PATH for Yandex Cloud CLI.
if [ -f '/home/m-nny/yandex-cloud/path.bash.inc' ]; then source '/home/m-nny/yandex-cloud/path.bash.inc'; fi

# The next line enables shell command completion for yc.
if [ -f '/home/m-nny/yandex-cloud/completion.zsh.inc' ]; then source '/home/m-nny/yandex-cloud/completion.zsh.inc'; fi
if [ -f '/opt/google-cloud-sdk/completion.zsh.inc' ]; then source '/opt/google-cloud-sdk/completion.zsh.inc'; fi


if [ -f '/home/m-nny/.local/bin/terraform' ]; then complete -o nospace -C /home/m-nny/.local/bin/terraform terraform; fi


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export PATH="$PATH:$(go env GOPATH)/bin"
